name: Build and Deploy on AWS
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make a new back-end envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_USERNAME: ${{secrets.POSTGRES_USERNAME}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          envkey_POSTGRES_DATABASE: ${{secrets.POSTGRES_DATABASE}}
          envket_POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
          envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
          envkey_JWT_SECRET: ${{secrets.JWT_SECRET}}
          directory: projeto22-autoral-back-end
          file_name: .env
          fail_on_empty: true
      - name: Make a new front-end envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_VITE_API_URL: ${{secrets.VITE_API_URL}}
          directory: projeto22-autoral-front-end
          file_name: .env
          fail_on_empty: true
      - name: Run docker compose down
        run: docker compose down
      - name: Delete react docker volume
        run: if docker volume ls --quiet --filter name=projeto-autoral_react-volume | grep -q .; then docker volume rm projeto-autoral_react-volume; fi
      - name: Run docker compose up
        run: docker compose up --build -d
